spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.222.136
    port: 6379
  application:
    name: ShopTalk-cart

server:
  port: 40000

gulimall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10