spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: ShopTalk-search
  session:
    store-type: redis
server:
  port: 12000
  servlet:
    #配置session过期时间
    session:
      timeout: 30m